#!/bin/sh

case "$1" in
  start)
    year=$(date +%Y)
    if [ "$year" -eq 1970 ]; then
        date -s "2025-01-01 00:00:00"
    fi
    ;;
  stop)
    ;;
  restart|reload)
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0
